# CASE WHEN을 통해 조건 분기 처리
SELECT
    ID,
    CASE 
        WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
        WHEN SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
        ELSE 'HIGH'
    END AS SIZE
FROM
    ECOLI_DATA 
ORDER BY
    ID