SELECT
    ugu.USER_ID,
    ugu.NICKNAME,
    SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_USER AS ugu
LEFT JOIN
    USED_GOODS_BOARD AS ugb
ON
    ugu.USER_ID = ugb.WRITER_ID
WHERE
    STATUS = 'DONE'
GROUP BY
    ugu.USER_ID,
    ugu.NICKNAME
HAVING
    TOTAL_SALES >= 700000
ORDER BY
    TOTAL_SALES