-- 코드를 입력하세요
# 틀린 풀이 
SELECT 
    DISTINCT 
        c.CAR_ID,
        c.CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 *(100 - crcd.DISCOUNT_RATE)/100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS c
INNER JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS ch
ON 
    c.CAR_ID = ch.CAR_ID
INNER JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS crcd
ON
    c.CAR_TYPE = crcd.CAR_TYPE
WHERE 
    c.CAR_TYPE IN ('세단', 'SUV') AND 
    (START_DATE < '2022-11-01' OR END_DATE > '2022-11-30') AND 
    DURATION_TYPE = '30일 이상'
ORDER BY 
    FEE DESC,
    CAR_TYPE,
    CAR_ID