SELECT
    ANIMAL_ID,
    OUT_NAME AS NAME
FROM (
SELECT
    O.ANIMAL_ID,
    O.NAME AS OUT_NAME,
    I.NAME AS IN_NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
) AS BASE
WHERE IN_NAME IS NULL AND OUT_NAME IS NOT NULL