SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM 
    (SELECT
    i.ID,
    ni.FISH_NAME,
    i.LENGTH,
    RANK() OVER (PARTITION BY i.FISH_TYPE ORDER BY LENGTH DESC) AS r
    FROM FISH_INFO AS i
    LEFT JOIN FISH_NAME_INFO AS ni
    ON i.FISH_TYPE = ni.FISH_TYPE
) AS fr
WHERE r = 1
ORDER BY ID ASC;