## LEFT JOIN과 INNER JOIN의 차이
SELECT
    d.DEPT_ID,
    d.DEPT_NAME_EN,
    ROUND(AVG(e.SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT AS d
JOIN HR_EMPLOYEES AS e
ON d.DEPT_ID = e.DEPT_ID
GROUP BY d.DEPT_ID, d.DEPT_NAME_EN
ORDER BY AVG_SAL DESC;