
###틀린 답

SELECT
    rh.HISTORY_ID,
    ROUND(
        c.DAILY_FEE *
        (DATEDIFF(rh.END_DATE, rh.START_DATE) + 1) *
        (1 - CASE
                WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 90 THEN 0.10
                WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 30 THEN 0.07
                WHEN DATEDIFF(rh.END_DATE, rh.START_DATE) + 1 >= 7  THEN 0.05
                ELSE 0
            END
        )
    ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS rh
ON c.CAR_ID = rh.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS dp
ON c.CAR_TYPE = dp.CAR_TYPE
WHERE c.CAR_TYPE = '트럭'
GROUP BY rh.HISTORY_ID, FEE
ORDER BY FEE DESC, rh.HISTORY_ID DESC;