###틀린 답

SELECT
    mp.MEMBER_NAME,
    rr.REVIEW_TEXT,
    rr.REVIEW_DATE
FROM MEMBER_PROFILE AS mp
LEFT JOIN REST_REVIEW AS rr
ON mp.MEMBER_ID = rr.MEMBER_ID
GROUP BY rr.MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1;