SELECT
    b.CATEGORY,
    SUM(sales) AS TOTAL_SALES
FROM BOOK AS b
LEFT JOIN BOOK_SALES AS bs
ON b.BOOK_ID = bs.BOOK_ID
WHERE
    bs.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY
    b.CATEGORY
ORDER BY b.CATEGORY ASC;