SELECT
    C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
ON C.CAR_ID = RH.CAR_ID
WHERE C.CAR_TYPE = "세단" AND 
EXTRACT(MONTH FROM RH.START_DATE) = 10
GROUP BY C.CAR_ID
ORDER BY CAR_ID DESC