-- https://school.programmers.co.kr/learn/courses/30/lessons/59411

SELECT
    ANIMAL_ID,
    i.NAME
FROM ANIMAL_INS AS i
LEFT JOIN ANIMAL_OUTS AS o
USING (ANIMAL_ID)
WHERE o.DATETIME IS NOT NULL
ORDER BY RANK() OVER (ORDER BY DATEDIFF(o.DATETIME, i.DATETIME) DESC)
LIMIT 2