WITH joined_2021 AS (
    SELECT
        *
    FROM
        USER_INFO
    WHERE
        EXTRACT(YEAR FROM JOINED) = '2021'
)

SELECT
    EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
    EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.USER_ID) / (SELECT COUNT(*) FROM joined_2021), 1) AS PUCHASED_RATIO
FROM
    joined_2021 AS j
LEFT JOIN
    ONLINE_SALE AS o
ON 
    j.USER_ID = o.USER_ID
GROUP BY
    YEAR,
    MONTH 
HAVING
    YEAR IS NOT NULL
ORDER BY 
    YEAR,
    MONTH 