-- https://school.programmers.co.kr/learn/courses/30/lessons/131532

SELECT
    DATE_FORMAT(SALES_DATE, '%Y') AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    GENDER,
    COUNT(DISTINCT USER_ID) AS USERS
FROM (
SELECT
    u.USER_ID,
    o.SALES_AMOUNT,
    o.SALES_DATE,
    u.GENDER
FROM ONLINE_SALE AS o
LEFT JOIN USER_INFO AS u
ON o.USER_ID= u.USER_ID
WHERE
    u.GENDER IS NOT NULL
) as b
GROUP BY
    DATE_FORMAT(SALES_DATE, '%Y'),
    DATE_FORMAT(SALES_DATE, '%m'),
    GENDER