-- 컬럼 : HISTORY_ID, FEE
-- 테이블 : CAR, HISTORY, PLAN
-- JOIN KEY : CAR_ID, CAR_TYPE
-- 조건 : 자동차 종류가 트럭 (CAR_TYPE="트럭")
WITH base AS(
    SELECT DISTINCT
        c.CAR_ID,
        DAILY_FEE,
        HISTORY_ID,
        DATEDIFF(END_DATE, START_DATE) AS DIFF_DAYS
        
    FROM CAR_RENTAL_COMPANY_CAR c
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h
    ON c.CAR_ID = h.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
    WHERE c.CAR_TYPE="트럭"
    GROUP BY
        c.CAR_ID,
        DAILY_FEE,
        HISTORY_ID
)
SELECT
    HISTORY_ID,
    CASE 
        WHEN DIFF_DAYS >= 90 THEN SUM(DAILY_FEE * 0.9)
        WHEN DIFF_DAYS >= 30 THEN SUM(DAILY_FEE * 0.93)
        WHEN DIFF_DAYS >= 7 THEN SUM(DAILY_FEE * 0.95)
        ELSE DAILY_FEE
    END AS FEE
FROM base
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC