-- 컬럼 : 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 
-- 테이블 : BOOK, BOOK_SALES, AUTHOR
-- JOIN_KEY : BOOK_ID, AUTHOR_ID
-- 정렬 : 저자ID 오름차순, 카테고리 내림차순
SELECT
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK_SALES bs
JOIN BOOK b
    USING(BOOK_ID)
JOIN AUTHOR a
    USING(AUTHOR_ID)
WHERE bs.SALES_DATE >= '2022-01-01'
  AND bs.SALES_DATE <  '2022-02-01'
GROUP BY
    a.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY
ORDER BY 
    a.AUTHOR_ID,
    b.CATEGORY DESC