-- 컬럼 : MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
-- 테이블 : MEMBER_PROFILE, REST_REVIEW
-- USING KEY : MEMBER_ID
SELECT
    MEMBER_NAME, 
    REVIEW_TEXT, 
    REVIEW_DATE,
    COUNT(MEMBER_NAME) AS CNT
FROM REST_REVIEW R
JOIN MEMBER_PROFILE M
USING(MEMBER_ID)
GROUP BY
    MEMBER_NAME, 
    REVIEW_TEXT, 
    REVIEW_DATE
# HAVING
#     COUNT(MEMBER_NAME) as cnt 
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
