WITH BASE AS (
    SELECT
        FISH_TYPE,
        ID,
        FISH_NAME,
        LENGTH,
        RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS R
    FROM FISH_INFO
    LEFT JOIN FISH_NAME_INFO
    USING (FISH_TYPE)
)

SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM BASE
WHERE 
    R = 1
ORDER BY
    ID 