-- ¿À´ä

WITH BASE AS (
    SELECT
        PRODUCT_ID,
        NEW_PRICE,
        MIN(CHANGE_DATE) OVER (ORDER BY PRODUCT_ID) AS M
    FROM PRODUCTS
)

SELECT
    PRODUCT_ID,
    CASE
        WHEN M <= '2019-08-16' THEN MAX(NEW_PRICE)
        WHEN M > '2019-08-16' THEN 10
    END AS PRICE
FROM BASE
GROUP BY
    PRODUCT_ID,
    M
