
SELECT
    DISTINCT USER_ID,
    NICKNAME,
    CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소',
    CONCAT(
        SUBSTRING(TLNO, 1, 3), '-',
        SUBSTRING(TLNO, 4, 4), '-',
        SUBSTRING(TLNO, 8, 4)
    ) AS '전화번호'
FROM (
    SELECT
        *,
        COUNT(WRITER_ID) OVER (PARTITION BY WRITER_ID) AS CNT
    FROM USED_GOODS_BOARD AS B
    LEFT JOIN USED_GOODS_USER AS U
    ON B.WRITER_ID = U.USER_ID
) AS BASE
WHERE CNT >=3
ORDER BY 
    USER_ID DESC