WITH BASE AS (
    SELECT
        DATE_TRUNC('MONTH',TRANS_DATE) AS T_D,
        ID,
        STATE,
        COUNTRY,
        AMOUNT
    FROM TRANSACTIONS
)


SELECT
    TO_CHAR(T_D,'YYYY-MM') AS MONTH,
    COUNTRY,
    COUNT(COUNTRY) AS TRANS_COUNT,
    CASE
        WHEN STATE='approved' THEN COUNT(COUNTRY)
        
        END AS APPROVED_COUNT,
    SUM(AMOUNT) TRANS_TOTAL_AMOUNT,
    CASE
        WHEN STATE='approved' THEN SUM(AMOUNT)
        END AS APPOVED_TOTAL_AMOUNT
FROM BASE
GROUP BY
    MONTH,
    COUNTRY,
    STATE
