SELECT
    HISTORY_ID,
    CASE
        WHEN DIFF < 6 THEN (DIFF+1)*DAILY_FEE
        WHEN DIFF < 29 THEN (DIFF+1)*DAILY_FEE*0.95
        WHEN DIFF < 89 THEN (DIFF+1)*DAILY_FEE*0.93
        ELSE (DIFF+1)*DAILY_FEE*0.9
    END AS FEE
FROM (
    SELECT
       HISTORY_ID,
       DAILY_FEE,
       DATEDIFF(END_DATE,START_DATE)AS DIFF
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
    USING (CAR_ID)
    WHERE CAR_TYPE = "트럭"
) AS BASE
ORDER BY
    FEE DESC,
    HISTORY_ID DESC