WITH BASE AS (
    SELECT
        FISH_TYPE,
        ID,
        CASE
            WHEN LENGTH <= 10 OR LENGTH IS NULL THEN 10
            ELSE LENGTH
            END AS LENGTH2
    FROM FISH_INFO
)

SELECT 
    COUNT(ID) AS FISH_COUNT,
    MAX(LENGTH2) AS MAX_LENGTH,
    FISH_TYPE
FROM (
    SELECT
        ID,
        FISH_TYPE,
        LENGTH2,
        AVG(LENGTH2) OVER(PARTITION BY FISH_TYPE) AS AVG_L
    FROM BASE
) AS BASE2
WHERE AVG_L >= 33
GROUP BY
    FISH_TYPE