SELECT
    AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK AS B
LEFT JOIN AUTHOR AS A
USING (AUTHOR_ID)
LEFT JOIN BOOK_SALES AS S
USING (BOOK_ID)
WHERE EXTRACT(YEAR FROM SALES_DATE) = 2022 AND EXTRACT(MONTH FROM SALES_DATE) = 01
GROUP BY
    AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY
ORDER BY
    AUTHOR_ID,
    CATEGORY DESC