SELECT
    MEMBER_NAME,
    REVIEW_TEXT,
    DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE,
    CNT
FROM(
    SELECT
        MEMBER_NAME,
        REVIEW_TEXT,
        REVIEW_DATE,
        COUNT(MEMBER_ID) OVER(PARTITION BY MEMBER_ID) AS CNT
    FROM REST_REVIEW AS R
    LEFT JOIN MEMBER_PROFILE AS M
    USING (MEMBER_ID)
    ORDER BY
        CNT DESC        
) AS BASE
WHERE CNT = (SELECT COUNT(MEMBER_ID)
                FROM REST_REVIEW`)