SELECT
    CATEGORY,
    SUM(SALES) AS TOTAL_SALES
FROM BOOK_SALES AS S
LEFT JOIN BOOK AS B
USING (BOOK_ID)
WHERE EXTRACT(YEAR FROM SALES_DATE)=2022 AND EXTRACT(MONTH FROM SALES_DATE)=01
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY